### ISSUE TITLE
Error running `sb accounts list`

### ISSUE THREAD

**Issue by mikeshultz** [mikeshultz/solidbyte#23]
Seen this error when running `sb accounts list`:

    Traceback (most recent call last):
      File "/home/mike/.venvs/skatter-contracts/bin/sb", line 11, in <module>
        load_entry_point('solidbyte', 'console_scripts', 'sb')()
      File "/home/mike/dev/solidbyte/solidbyte/cli/handler.py", line 65, in main
        IMPORTED_MODULES[args.command].main(parser_args=args)
      File "/home/mike/dev/solidbyte/solidbyte/cli/accounts.py", line 45, in main
        network_name = collapse_oel(parser_args.network)
      File "/home/mike/dev/solidbyte/solidbyte/common/__init__.py", line 25, in collapse_oel
        raise ValueError("Not a list")
    ValueError: Not a list

Keystore has 2 files.

**Comment by mikeshultz** [comment]
Fix in, but stuck in install branch for the time being.
