### ISSUE TITLE
Deployment error with bytecode formatting

### ISSUE THREAD

**Issue by mikeshultz** [mikeshultz/solidbyte#24]
Seen when deploying to test network.

    Traceback (most recent call last):
      File "/home/mike/.venvs/skatter-contracts/lib/python3.7/site-packages/web3/utils/formatters.py", line 68, in apply_formatters_to_dict
        yield key, formatters[key](item)
      File "/home/mike/.venvs/skatter-contracts/lib/python3.7/site-packages/web3/utils/normalizers.py", line 190, in normalize_bytecode
        bytecode = HexBytes(bytecode)
      File "/home/mike/.venvs/skatter-contracts/lib/python3.7/site-packages/hexbytes/main.py", line 17, in __new__
        bytesval = hexstr_if_str(to_bytes, val)
      File "/home/mike/.venvs/skatter-contracts/lib/python3.7/site-packages/eth_utils/conversions.py", line 146, in hexstr_if_str
        hexstr_or_primitive
    ValueError: when sending a str, it must be a hex string. Got:

**Comment by mikeshultz** [comment]
Traceback (most recent call last):
      File "/home/mike/.venvs/skatter-contracts/bin/sb", line 11, in <module>
        load_entry_point('solidbyte', 'console_scripts', 'sb')()
      File "/home/mike/dev/solidbyte/solidbyte/cli/handler.py", line 65, in main
        IMPORTED_MODULES[args.command].main(parser_args=args)
      File "/home/mike/dev/solidbyte/solidbyte/cli/deploy.py", line 37, in main
        deployer.deploy()
      File "/home/mike/dev/solidbyte/solidbyte/deploy/__init__.py", line 191, in deploy
        retval = script.main(**script_kwargs)
      File "/home/mike/dev/skatter-contracts/deploy/deploy_main.py", line 37, in main
        sb = SkatterBid.deployed(env.address)
      File "/home/mike/dev/solidbyte/solidbyte/deploy/objects.py", line 159, in deployed
        raise e
      File "/home/mike/dev/solidbyte/solidbyte/deploy/objects.py", line 156, in deployed
        return self._deploy(*args, **kwargs)
      File "/home/mike/dev/solidbyte/solidbyte/deploy/objects.py", line 121, in _deploy
        }, *args, **kwargs)
      File "/home/mike/dev/solidbyte/solidbyte/common/web3/__init__.py", line 16, in create_deploy_tx
        raise e
      File "/home/mike/dev/solidbyte/solidbyte/common/web3/__init__.py", line 11, in create_deploy_tx
        inst = web3.eth.contract(abi=abi, bytecode=bytecode)
      File "/home/mike/.venvs/skatter-contracts/lib/python3.7/site-packages/web3/eth.py", line 367, in contract
        ContractFactory = ContractFactoryClass.factory(self.web3, **kwargs)
      File "/home/mike/.venvs/skatter-contracts/lib/python3.7/site-packages/web3/contract.py", line 262, in factory
        normalizers=normalizers)
      File "/home/mike/.venvs/skatter-contracts/lib/python3.7/site-packages/web3/utils/datatypes.py", line 33, in __new__
        namespace)
      File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
      File "/home/mike/.venvs/skatter-contracts/lib/python3.7/site-packages/eth_utils/functional.py", line 46, in inner
        return callback(fn(*args, **kwargs))
      File "/home/mike/.venvs/skatter-contracts/lib/python3.7/site-packages/web3/utils/formatters.py", line 70, in apply_formatters_to_dict
        raise type(exc)("Could not format value %r as field %r" % (item, key)) from exc
    ValueError: Could not format value

**Comment by mikeshultz** [comment]
This unlocked a whole chain of bugs that got taken care of in the `install` branch.
