### ISSUE TITLE
Bytecode hash not taking links into account

### ISSUE THREAD

**Issue by mikeshultz** [mikeshultz/solidbyte#40]
The bytecode hashing, for tracking of deploy requirements, is failing because links aren't resolved.

    Traceback (most recent call last):
      File "/usr/lib/python3.7/encodings/hex_codec.py", line 19, in hex_decode
        return (binascii.a2b_hex(input), len(input))
    binascii.Error: Non-hexadecimal digit found

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "/home/mike/.venvs/skatter-contracts/lib/python3.7/site-packages/solidbyte-0.6.0-py3.7.egg/solidbyte/deploy/objects.py", line 249, in _deploy
        bytecode_hash = hash_hexstring(clean_bytecode(self.source_bytecode))
      File "/home/mike/.venvs/skatter-contracts/lib/python3.7/site-packages/solidbyte-0.6.0-py3.7.egg/solidbyte/common/web3/__init__.py", line 39, in hash_hexstring
        return normalize_hexstring(Web3.sha3(hexstr=normalize_hexstring(hexbytes)))
      File "/home/mike/.venvs/skatter-contracts/lib/python3.7/site-packages/eth_utils/functional.py", line 46, in inner
        return callback(fn(*args, **kwargs))
      File "/home/mike/.venvs/skatter-contracts/lib/python3.7/site-packages/web3/main.py", line 138, in sha3
        input_bytes = to_bytes(primitive, hexstr=hexstr, text=text)
      File "/home/mike/.venvs/skatter-contracts/lib/python3.7/site-packages/web3/utils/encoding.py", line 155, in to_bytes
        return decode_hex(hexstr)
      File "/home/mike/.venvs/skatter-contracts/lib/python3.7/site-packages/eth_utils/hexadecimal.py", line 17, in decode_hex
        return codecs.decode(remove_0x_prefix(value), "hex")  # type: ignore
    binascii.Error: decoding with 'hex' codec failed (Error: Non-hexadecimal digit found)

**Comment by mikeshultz** [comment]
Snippet of the bytecode: 

    [...] 839273__$13811623e8434e588b8942cf9304d14b96$__92639 [...]

**Comment by mikeshultz** [comment]
Maybe should take this into account as well while working on this:

https://github.com/mikeshultz/solidbyte/blob/master/solidbyte/deploy/objects.py#L246

**Comment by mikeshultz** [comment]
Fixed in PR #45.  What this now does, is replace links with a false address that's just a keccak hash of the name of the contract.  This way, the deployment state of the linked libraries is irrelevant to detect code changes.
