### ISSUE TITLE
Error with accounts list if no JSON-RPC provider availible

### ISSUE THREAD

**Issue by mikeshultz** [mikeshultz/solidbyte#59]
If there's no JSON-RPC provider, account operations should still work.  Getting a balance for the account should not be a deal breaker.

    Traceback (most recent call last):
      File "/home/travis/virtualenv/python3.6.3/bin/sb", line 11, in <module>
        load_entry_point('solidbyte==0.7.5', 'console_scripts', 'sb')()
      File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/solidbyte-0.7.5-py3.6.egg/solidbyte/cli/handler.py", line 85, in main
        IMPORTED_MODULES[args.command].main(parser_args=args)
      File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/solidbyte-0.7.5-py3.6.egg/solidbyte/cli/accounts.py", line 94, in main
        for a in accts.get_accounts():
      File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/solidbyte-0.7.5-py3.6.egg/solidbyte/accounts/__init__.py", line 26, in wrapper
        args[0]._load_accounts()
      File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/solidbyte-0.7.5-py3.6.egg/solidbyte/accounts/__init__.py", line 113, in _load_accounts
        self.web3.eth.getBalance(self.web3.toChecksumAddress(addr)),
      File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/web3/eth.py", line 108, in getBalance
        [account, block_identifier],
      File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/web3/manager.py", line 109, in request_blocking
        response = self._make_request(method, params)
      File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/web3/manager.py", line 101, in _make_request
        params,
    web3.exceptions.UnhandledRequest: No providers responded to the RPC request:
    method:eth_getBalance

**Comment by mikeshultz** [comment]
This seems to have already been cleared up.

    Traceback (most recent call last):
      File "/home/mike/.venvs/solidbyte/bin/sb", line 11, in <module>
        load_entry_point('solidbyte', 'console_scripts', 'sb')()
      File "/home/mike/dev/solidbyte/solidbyte/cli/handler.py", line 85, in main
        IMPORTED_MODULES[args.command].main(parser_args=args)
      File "/home/mike/dev/solidbyte/solidbyte/cli/accounts.py", line 71, in main
        web3 = web3c.get_web3(network_name)
      File "/home/mike/dev/solidbyte/solidbyte/common/web3/connection.py", line 159, in get_web3
        raise SolidbyteException("Unable to connect to node")
    solidbyte.common.exceptions.SolidbyteException: Unable to connect to node
