### ISSUE TITLE
Test vyper interfaces

### ISSUE THREAD

**Issue by mikeshultz** [mikeshultz/solidbyte#64]
Vyper linking needs to be double checked to make sure it works.  Add relevant tests as well.

**Comment by mikeshultz** [comment]
Well, there's no linking with vyper.  So, I guess test interfaces at least.

**Comment by mikeshultz** [comment]
So, right now sb tries to compile these interface files.  This results in the compiler throwing `StructureException`.

    Traceback (most recent call last):
      File "/home/mike/.venvs/solidbyte/bin/vyper", line 153, in <module>
        interface_codes=interface_codes
      File "/home/mike/.venvs/solidbyte/lib/python3.7/site-packages/vyper/compiler.py", line 227, in compile_codes
        exc_handler(contract_name, exc)
      File "/home/mike/.venvs/solidbyte/bin/vyper", line 82, in exc_handler
        raise exception
      File "/home/mike/.venvs/solidbyte/lib/python3.7/site-packages/vyper/compiler.py", line 223, in compile_codes
        interface_codes=interface_codes,
      File "/home/mike/.venvs/solidbyte/lib/python3.7/site-packages/vyper/compiler.py", line 148, in _mk_bytecode_output
        return '0x' + __compile(code, interface_codes=interface_codes).hex()
      File "/home/mike/.venvs/solidbyte/lib/python3.7/site-packages/vyper/compiler.py", line 31, in __compile
        runtime_only=kwargs.get('bytecode_runtime', False)
      File "/home/mike/.venvs/solidbyte/lib/python3.7/site-packages/vyper/parser/parser.py", line 237, in parse_tree_to_lll
        o, otherfuncs, sigs, external_contracts, origcode, global_ctx, defaultfunc, runtime_only
      File "/home/mike/.venvs/solidbyte/lib/python3.7/site-packages/vyper/parser/parser.py", line 162, in parse_other_functions
        sub.append(parse_func(_def, {**{'self': sigs}, **external_contracts}, origcode, global_ctx))
      File "/home/mike/.venvs/solidbyte/lib/python3.7/site-packages/vyper/parser/parser.py", line 670, in parse_func
        ] + nonreentrant_post + stop_func
      File "/home/mike/.venvs/solidbyte/lib/python3.7/site-packages/vyper/parser/parser.py", line 668, in <listcomp>
        for c
      File "/home/mike/.venvs/solidbyte/lib/python3.7/site-packages/vyper/parser/parser.py", line 688, in parse_body
        return parse_stmt(code, context)
      File "/home/mike/.venvs/solidbyte/lib/python3.7/site-packages/vyper/parser/parser.py", line 703, in parse_stmt
        return Stmt(stmt, context).lll_node
      File "/home/mike/.venvs/solidbyte/lib/python3.7/site-packages/vyper/parser/stmt.py", line 79, in __init__
        self.lll_node = self.stmt_table[stmt_type]()
      File "/home/mike/.venvs/solidbyte/lib/python3.7/site-packages/vyper/parser/stmt.py", line 84, in expr
        return Stmt(self.stmt.value, self.context).lll_node
      File "/home/mike/.venvs/solidbyte/lib/python3.7/site-packages/vyper/parser/stmt.py", line 79, in __init__
        self.lll_node = self.stmt_table[stmt_type]()
      File "/home/mike/.venvs/solidbyte/lib/python3.7/site-packages/vyper/parser/stmt.py", line 95, in parse_name
        raise StructureException("Unsupported statement type: %s" % type(self.stmt), self.stmt)
    vyper.exceptions.StructureException: line 4: Unsupported statement type: <class '_ast.Name'>
    def owner() -> address: constant
    ------------------------^

This is an issue with vyper since it dies and the returncode indicates an error.  For solidity, it terminates fine and returns no bytecode, which we ID and issue a warning for.  This also isn't great.

I think sb needs a way to detect both solidity and vyper interfaces and exclude them from the sb compiler compilation process.   I'm going to wrap these together in a new issue.

**Comment by mikeshultz** [comment]
Well, tested and failed.  On to #74
